ToDo/ToDo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Todoapp.urls')),
]

ToDo/Todoapp/urls.py
from django.urls import path
from . import views

app_name = 'ToDoApp'

urlpatterns = [
    path('', views.index, name="todo"),
    path('/del/<int:item_id>/', views.remove, name="del"),
]

ToDo/Todoapp/models.py
from django.db import models
from django.utils import timezone


class ToDo(models.Model):
    Task = models.TextField( max_length=200 )
    created = models.DateTimeField(default=timezone.now)
    tasktime = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

ToDo/Todoapp/forms.py
from django import forms
from .models import ToDo


class ToDoForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ('Task', 'tasktime')

ToDo/Todoapp/views.py
from django.shortcuts import render, redirect
from .models import ToDo
from .forms import ToDoForm


def index(request):
    item_list = ToDo.objects.order_by("-created")
    if request.method == 'POST':
        task_form = ToDoForm(request.POST)
        if task_form.is_valid():
            task_form.save()
            return redirect('ToDoApp:todo')
    task_form = ToDoForm()

    page = {
        "forms": task_form,
        "list": item_list,
    }
    return render(request, 'index.html', page)


def remove(request, item_id):
    item = ToDo.objects.get(id=item_id)
    item.delete()
    return redirect('ToDoApp:todo')

ToDo/Todoapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ToDo</title>
</head>
<body>
<form action="" method="POST">
    {{ forms.as_p }}
    {% csrf_token %}
    <input type="submit">
</form>

<table border="solid">
    <tr>
        <th>Task pending</th>
        <th>Added time</th>
        <th>Task time</th>
    </tr>
    {% for task in list %}
        <tr>
            <td>{{ task.Task }}</td>
            <td>{{ task.created }}</td>
            <td>{{ task.tasktime }}</td>
            <td>
               <a href="{% url 'ToDoApp:del' task.id %}">remove</a>
            </td>
        </tr>
    {% endfor %}
</table>
</body>
</html>